#
# Makefile for cfg library
#
# Copyright (C) 2009 Broadcom Corporation
#
# $Id: Makefile,v 1.2 2010-02-10 22:37:24 $
#

SRCBASE = ../../..
include ../secfrw_defines.mk

SRCS = bcmseclib_api.c cfg.c

TARGET_LIB=cfg

include ../secfrw_rules.mk
