#
# Makefile for cfg library
#
# Copyright (C) 2009 Broadcom Corporation
#
# $Id: Makefile,v 1.2 2010-02-10 22:37:28 $
#

SRCBASE = ../../..
include ../secfrw_defines.mk

SRCS = dev.c dev_wlan.c pp_cfg.c bcmsec_sprintf.c events.c

TARGET_LIB=linux

include ../secfrw_rules.mk
