#
# Makefile for dispatcher library
#
# Copyright (C) 2009 Broadcom Corporation
#
# $Id: Makefile,v 1.2 2010-02-10 22:37:26 $
#

SRCBASE = ../../..
include ../secfrw_defines.mk

SRCS = disp_linux.c

TARGET_LIB=disp

include ../secfrw_rules.mk
